//! Autogenerated weights for pallet_locker_mirror
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-02-09, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./scripts/../target/release/subsocial-node
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// Compiled
// --pallet
// pallet_locker_mirror
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --output
// ./pallets/locker-mirror/src/weights.rs
// --template
// ./.maintain/weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_locker_mirror.
pub trait WeightInfo {
    fn set_locked_info() -> Weight;
    fn clear_locked_info() -> Weight;
    fn set_last_processed_locker_event() -> Weight;
}

/// Weights for pallet_locker_mirror using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
            // Storage: unknown [0xca15211defb6ae0af15535cfecffe8c11afdac6006e1f5e457c882416ea1d17a] (r:0 w:1)
        fn set_locked_info() -> Weight {
        (25_000_000 as Weight)
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: unknown [0xca15211defb6ae0af15535cfecffe8c11afdac6006e1f5e457c882416ea1d17a] (r:0 w:1)
        fn clear_locked_info() -> Weight {
        (24_000_000 as Weight)
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: unknown [0xca15211defb6ae0af15535cfecffe8c134853d48f12e991904ee9a1e3f8bd702] (r:0 w:1)
        fn set_last_processed_locker_event() -> Weight {
        (23_000_000 as Weight)
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: unknown [0xca15211defb6ae0af15535cfecffe8c11afdac6006e1f5e457c882416ea1d17a] (r:0 w:1)
        fn set_locked_info() -> Weight {
        (25_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: unknown [0xca15211defb6ae0af15535cfecffe8c11afdac6006e1f5e457c882416ea1d17a] (r:0 w:1)
        fn clear_locked_info() -> Weight {
        (24_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: unknown [0xca15211defb6ae0af15535cfecffe8c134853d48f12e991904ee9a1e3f8bd702] (r:0 w:1)
        fn set_last_processed_locker_event() -> Weight {
        (23_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
    }
